---
# This file is managed centrally by modulesync
#   https://github.com/maestrodev/puppet-modulesync

before_install:
  - rm -f Gemfile.lock

rvm:
  - "2.1.8"

env:
  - PUPPET_VERSION="~> 4.10.0"
  - PUPPET_VERSION="~> 5.5.0"

matrix:
  exclude:
    - rvm: 2.4.0
      env: PUPPET_VERSION="~> 5.5.0"